const ClienteDetailsActionTypes = {
      ADD_INFO_CLIENT: "ADD_INFO_CLIENT",
      ADD_LAST_CONTACT: "ADD_LAST_CONTACT",
      ADD_LAST_CONTACTS: "ADD_LAST_CONTACTS",
      CREATE_MESSAGES: "CREATE_MESSAGES",
      ADD_MESSAGES: "ADD_MESSAGES",
      ACCEPT_ANWSER: "ACCEPT_ANWSER",
      CHANGE_STATUS_QUEUE: "CHANGE_STATUS_QUEUE",
  };
  
  export default ClienteDetailsActionTypes;