const UserActionTypes = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGIN_START: "USER_LOGIN_START",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  GET_USER_INFO: "GET_USER_INFO",
  USER_LOGOUT: "USER_LOGOUT"
};

export default UserActionTypes;
