const ModalActionTypes = {
  SHOW_MODAL_EDIT_FOLDER: "SHOW_MODAL_EDIT_FOLDER",
  SHOW_MODAL_ADD_FOLDER: "SHOW_MODAL_ADD_FOLDER",
  SHOW_MODAL_DELETE_FOLDER: "SHOW_MODAL_DELETE_FOLDER",
  SHOW_MODAL_MOVE_FOLDER: "SHOW_MODAL_MOVE_FOLDER",
  SHOW_MODAL_FLUXO: "SHOW_MODAL_FLUXO",
  SHOW_MODAL_CONF_FLUXO: "SHOW_MODAL_CONF_FLUXO"
};

export default ModalActionTypes;
